format = """\
$username\
$hostname\
$directory\
$kubernetes\
$terraform\
$python\
$git_branch\
$git_status\
$cmd_duration\
$all\
$character"""


add_newline = true

[line_break]
disabled = false

[username]
style_user = "white"
style_root = "white"
format = " [$user]($style)@"
disabled = true
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold yellow) "
disabled = true

#[battery]
#full_symbol = "🔋"
#charging_symbol = "⚡️"
#discharging_symbol = "🔋"

#[[battery.display]]
#threshold = 99
#style = "bold red"

[directory]
truncation_length = 3
truncation_symbol = ".../"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "[$path]($style)[$read_only]($read_only_style) "

[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold purple) '
#detect_extensions = ['yaml','yml']
disabled = false

[terraform]
format = "via [ $version]($style) "
disabled = false

[python]
symbol = " "
python_binary = "python"
disabled = false

[git_branch]
symbol = "󰊢"
format = "on [$symbol$branch]($style) "
truncation_length = 20
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "  "
modified = "[ ](fg:124)"
staged = '[++\($count\)](green)'
renamed = "󰑕 "
deleted = " "

[cmd_duration]
min_time = 500
format = " [$duration](bold yellow) "

[docker_context]
disabled = true

[gcloud]
disabled = false
detect_env_vars = ['CLOUDSDK_ACTIVE_CONFIG_NAME', 'GOOGLE_APPLICATION_CREDENTIALS']
symbol = "☁️  "
format = 'on [$symbol$account(@$domain)(\($region\))]($style) '

[character]
success_symbol = "[❯](fg:green)"
error_symbol = "[✗](fg:124)"
